#ifndef ORANGEBUS_H
#define ORANGEBUS_H

#include "esp_err.h"
#include <stdint.h>
#include <stdbool.h>

#define ORANGEBUS_I2S_BCK 26
#define ORANGEBUS_I2S_WS 25
#define ORANGEBUS_I2S_DATA 22
#define ORANGEBUS_I2S_MCLK 0
#define ORANGEBUS_I2S_MIC_DATA 35

#define ORANGEBUS_IBUS_TX 17
#define ORANGEBUS_IBUS_RX 16

#define ORANGEBUS_IBUS_UART_NUM UART_NUM_2
#define ORANGEBUS_IBUS_BAUD 9600
#define ORANGEBUS_IBUS_RX_BUF_SIZE 256
#define ORANGEBUS_IBUS_TX_BUF_SIZE 128
#define ORANGEBUS_IBUS_MAX_PKT 64

#define ORANGEBUS_IBUS_PKT_SRC 0
#define ORANGEBUS_IBUS_PKT_LEN 1
#define ORANGEBUS_IBUS_PKT_DST 2
#define ORANGEBUS_IBUS_PKT_CMD 3
#define ORANGEBUS_IBUS_PKT_DB1 4

#define ORANGEBUS_IBUS_DEV_GM 0x00
#define ORANGEBUS_IBUS_DEV_CDC 0x18
#define ORANGEBUS_IBUS_DEV_FUH 0x28
#define ORANGEBUS_IBUS_DEV_CCM 0x30
#define ORANGEBUS_IBUS_DEV_GT 0x3B
#define ORANGEBUS_IBUS_DEV_DIA 0x3F
#define ORANGEBUS_IBUS_DEV_EWS 0x44
#define ORANGEBUS_IBUS_DEV_CID 0x46
#define ORANGEBUS_IBUS_DEV_MFL 0x50
#define ORANGEBUS_IBUS_DEV_IHK 0x5B
#define ORANGEBUS_IBUS_DEV_PDC 0x60
#define ORANGEBUS_IBUS_DEV_RAD 0x68
#define ORANGEBUS_IBUS_DEV_DSP 0x6A
#define ORANGEBUS_IBUS_DEV_SM0 0x72
#define ORANGEBUS_IBUS_DEV_SDRS 0x73
#define ORANGEBUS_IBUS_DEV_CDCD 0x76
#define ORANGEBUS_IBUS_DEV_NAVE 0x7F
#define ORANGEBUS_IBUS_DEV_IKE 0x80
#define ORANGEBUS_IBUS_DEV_SES 0xB0
#define ORANGEBUS_IBUS_DEV_JNAV 0xBB
#define ORANGEBUS_IBUS_DEV_GLO 0xBF
#define ORANGEBUS_IBUS_DEV_MID 0xC0
#define ORANGEBUS_IBUS_DEV_TEL 0xC8
#define ORANGEBUS_IBUS_DEV_TCU 0xCA
#define ORANGEBUS_IBUS_DEV_LCM 0xD0
#define ORANGEBUS_IBUS_DEV_IRIS 0xE0
#define ORANGEBUS_IBUS_DEV_ANZV 0xE7
#define ORANGEBUS_IBUS_DEV_VM 0xED
#define ORANGEBUS_IBUS_DEV_BMBT 0xF0
#define ORANGEBUS_IBUS_DEV_LOC 0xFF

#define ORANGEBUS_IBUS_CMD_CDC_REQUEST 0x38
#define ORANGEBUS_IBUS_CMD_CDC_RESPONSE 0x39
#define ORANGEBUS_IBUS_CMD_VOL_CTRL 0x32
#define ORANGEBUS_IBUS_CMD_MOD_STATUS_REQ 0x01
#define ORANGEBUS_IBUS_CMD_MOD_STATUS_RESP 0x02
#define ORANGEBUS_IBUS_CMD_IKE_IGN_REQ 0x10
#define ORANGEBUS_IBUS_CMD_IKE_IGN_RESP 0x11

#define ORANGEBUS_IBUS_CDC_CMD_GET_STATUS 0x00
#define ORANGEBUS_IBUS_CDC_CMD_STOP_PLAYING 0x01
#define ORANGEBUS_IBUS_CDC_CMD_PAUSE_PLAYING 0x02
#define ORANGEBUS_IBUS_CDC_CMD_START_PLAYING 0x03
#define ORANGEBUS_IBUS_CDC_CMD_CHANGE_TRACK 0x0A
#define ORANGEBUS_IBUS_CDC_CMD_CHANGE_TRACK_BL 0x05

#define ORANGEBUS_IBUS_CDC_STAT_STOP 0x00
#define ORANGEBUS_IBUS_CDC_STAT_PLAYING 0x02
#define ORANGEBUS_IBUS_CDC_FUNC_NOT_PLAY 0x02
#define ORANGEBUS_IBUS_CDC_FUNC_PLAYING 0x09
#define ORANGEBUS_IBUS_CDC_DISC_ALL 0x3F

#define ORANGEBUS_IBUS_TEL_CMD_LED_STATUS 0x2B
#define ORANGEBUS_IBUS_TEL_CMD_STATUS 0x2C
#define ORANGEBUS_IBUS_TEL_CMD_TITLE_TEXT 0x23

#define ORANGEBUS_IBUS_TEL_STATUS_NONE 0x00
#define ORANGEBUS_IBUS_TEL_STATUS_POWER_HF 0x10
#define ORANGEBUS_IBUS_TEL_STATUS_POWER_CALL 0x35

#define ORANGEBUS_IBUS_TEL_LED_OFF 0x00
#define ORANGEBUS_IBUS_TEL_LED_GREEN_BLINK 0x30
#define ORANGEBUS_IBUS_TEL_LED_GREEN_ON 0x10
#define ORANGEBUS_IBUS_TEL_LED_RED_ON 0x01

#define ORANGEBUS_IBUS_TEL_TITLE_DEFAULT 0x00
#define ORANGEBUS_IBUS_TEL_TITLE_ON_CALL 0x02
#define ORANGEBUS_IBUS_TEL_TITLE_OPT_SET 0x30

#define ORANGEBUS_IBUS_IGNITION_OFF 0x00
#define ORANGEBUS_IBUS_IGNITION_KLR 0x01
#define ORANGEBUS_IBUS_IGNITION_KL15 0x03

#define ORANGEBUS_IBUS_MID_CMD_MODE 0x20
#define ORANGEBUS_IBUS_MID_CMD_SET_MODE 0x27
#define ORANGEBUS_IBUS_MID_BUTTON_PRESS 0x31
#define ORANGEBUS_IBUS_MID_MAX_CHARS 24

#define ORANGEBUS_IBUS_RAD_VOL_DOWN 0x00
#define ORANGEBUS_IBUS_RAD_VOL_UP 0x01

#define ORANGEBUS_IBUS_MFL_BTN_SPEAK 0x01
#define ORANGEBUS_IBUS_MFL_BTN_VOL_UP 0x11
#define ORANGEBUS_IBUS_MFL_BTN_VOL_DOWN 0x10

#define ORANGEBUS_IBUS_DSP_CMD_CONFIG_SET 0x36
#define ORANGEBUS_IBUS_DSP_CFG_INPUT_RADIO 0xA1
#define ORANGEBUS_IBUS_DSP_CFG_INPUT_SPDIF 0xA0

#define ORANGEBUS_IBUS_CMD_GT_WRITE_TITLE 0x23
#define ORANGEBUS_IBUS_CMD_GT_WRITE_ZONE 0x62
#define ORANGEBUS_IBUS_CMD_GT_WRITE_INDEX 0x60
#define ORANGEBUS_IBUS_CMD_GT_CLEAR 0x63

#define ORANGEBUS_IBUS_MIR_MAX_CHARS 11

typedef enum {
    ORANGEBUS_A2DP_IDLE = 0,
    ORANGEBUS_A2DP_CONNECTING,
    ORANGEBUS_A2DP_CONNECTED,
    ORANGEBUS_A2DP_PLAYING,
    ORANGEBUS_A2DP_PAUSED,
} orangebus_a2dp_state_t;

typedef enum {
    ORANGEBUS_HFP_IDLE = 0,
    ORANGEBUS_HFP_CONNECTED,
    ORANGEBUS_HFP_AUDIO_OPEN,
    ORANGEBUS_HFP_INCOMING,
    ORANGEBUS_HFP_OUTGOING,
    ORANGEBUS_HFP_ACTIVE,
} orangebus_hfp_state_t;

typedef enum {
    ORANGEBUS_IBUS_EVT_CDC_STATUS_REQ = 0,
    ORANGEBUS_IBUS_EVT_CDC_BUTTON_PRESS,
    ORANGEBUS_IBUS_EVT_MFL_BUTTON_PRESS,
    ORANGEBUS_IBUS_EVT_IGNITION_STATUS,
    ORANGEBUS_IBUS_EVT_VOLUME_CHANGE,
    ORANGEBUS_IBUS_EVT_MID_BUTTON_PRESS,
    ORANGEBUS_IBUS_EVT_MID_MODE_CHANGE,
    ORANGEBUS_IBUS_EVT_BMBT_BUTTON_PRESS,
    ORANGEBUS_IBUS_EVT_GT_MENU_SELECT,
    ORANGEBUS_IBUS_EVT_GT_CHANGE_UI_REQ,
    ORANGEBUS_IBUS_EVT_PDC_STATUS,
    ORANGEBUS_IBUS_EVT_COUNT,
} orangebus_ibus_event_t;

typedef void (*orangebus_ibus_cb_t)(uint8_t *data, uint8_t len);

typedef enum {
    ORANGEBUS_UI_MODE_CD53 = 1,
    ORANGEBUS_UI_MODE_BMBT = 2,
    ORANGEBUS_UI_MODE_MID = 3,
    ORANGEBUS_UI_MODE_MIR = 5,
} orangebus_ui_mode_t;

typedef enum {
    ORANGEBUS_COMFORT_GM_UNKNOWN = 0,
    ORANGEBUS_COMFORT_GM_ZKE3_GM1,
    ORANGEBUS_COMFORT_GM_ZKE3_GM5,
    ORANGEBUS_COMFORT_GM_ZKE5,
} orangebus_comfort_gm_variant_t;

typedef enum {
    ORANGEBUS_COMFORT_LM_UNKNOWN = 0,
    ORANGEBUS_COMFORT_LM_LME38,
    ORANGEBUS_COMFORT_LM_LCM,
    ORANGEBUS_COMFORT_LM_LCM_II,
    ORANGEBUS_COMFORT_LM_LSZ,
} orangebus_comfort_lm_variant_t;

typedef struct {
    char title[81];
    char artist[81];
    char album[81];
} orangebus_metadata_t;

typedef struct audio_output_t audio_output_t;
typedef struct avrcp_controller_t avrcp_controller_t;
typedef struct a2dp_sink_t a2dp_sink_t;
typedef struct hfp_client_t hfp_client_t;
typedef struct cli_t cli_t;
typedef struct eq_processor_t eq_processor_t;
typedef struct spp_server_t spp_server_t;
typedef struct ibus_t ibus_t;
typedef struct ibus_config_t ibus_config_t;
typedef struct cdc_t cdc_t;
typedef struct tel_t tel_t;
typedef struct ui_cd53_t ui_cd53_t;
typedef struct ui_mir_t ui_mir_t;
typedef struct ui_mid_t ui_mid_t;
typedef struct ui_bmbt_t ui_bmbt_t;
typedef struct comfort_t comfort_t;

#endif
