#ifndef IBUS_PROTOCOL_H
#define IBUS_PROTOCOL_H

#include <stdint.h>

/* --- Offsety pol w pakiecie I-BUS --- */
#define ORANGEBUS_IBUS_PKT_SRC 0
#define ORANGEBUS_IBUS_PKT_LEN 1
#define ORANGEBUS_IBUS_PKT_DST 2
#define ORANGEBUS_IBUS_PKT_CMD 3
#define ORANGEBUS_IBUS_PKT_DB1 4

/* --- Adresy urzadzen na magistrali I-BUS --- */
#define ORANGEBUS_IBUS_DEV_GM 0x00
#define ORANGEBUS_IBUS_DEV_CDC 0x18
#define ORANGEBUS_IBUS_DEV_FUH 0x28
#define ORANGEBUS_IBUS_DEV_CCM 0x30
#define ORANGEBUS_IBUS_DEV_GT 0x3B
#define ORANGEBUS_IBUS_DEV_DIA 0x3F
#define ORANGEBUS_IBUS_DEV_EWS 0x44
#define ORANGEBUS_IBUS_DEV_CID 0x46
#define ORANGEBUS_IBUS_DEV_MFL 0x50
#define ORANGEBUS_IBUS_DEV_IHK 0x5B
#define ORANGEBUS_IBUS_DEV_PDC 0x60
#define ORANGEBUS_IBUS_DEV_RAD 0x68
#define ORANGEBUS_IBUS_DEV_DSP 0x6A
#define ORANGEBUS_IBUS_DEV_SM0 0x72
#define ORANGEBUS_IBUS_DEV_SDRS 0x73
#define ORANGEBUS_IBUS_DEV_CDCD 0x76
#define ORANGEBUS_IBUS_DEV_NAVE 0x7F
#define ORANGEBUS_IBUS_DEV_IKE 0x80
#define ORANGEBUS_IBUS_DEV_SES 0xB0
#define ORANGEBUS_IBUS_DEV_JNAV 0xBB
#define ORANGEBUS_IBUS_DEV_GLO 0xBF
#define ORANGEBUS_IBUS_DEV_MID 0xC0
#define ORANGEBUS_IBUS_DEV_TEL 0xC8
#define ORANGEBUS_IBUS_DEV_TCU 0xCA
#define ORANGEBUS_IBUS_DEV_LCM 0xD0
#define ORANGEBUS_IBUS_DEV_IRIS 0xE0
#define ORANGEBUS_IBUS_DEV_ANZV 0xE7
#define ORANGEBUS_IBUS_DEV_VM 0xED
#define ORANGEBUS_IBUS_DEV_BMBT 0xF0
#define ORANGEBUS_IBUS_DEV_LOC 0xFF

/* --- Komendy ogolne I-BUS --- */
#define ORANGEBUS_IBUS_CMD_CDC_REQUEST 0x38
#define ORANGEBUS_IBUS_CMD_CDC_RESPONSE 0x39
#define ORANGEBUS_IBUS_CMD_VOL_CTRL 0x32
#define ORANGEBUS_IBUS_CMD_MOD_STATUS_REQ 0x01
#define ORANGEBUS_IBUS_CMD_MOD_STATUS_RESP 0x02
#define ORANGEBUS_IBUS_CMD_IKE_IGN_REQ 0x10
#define ORANGEBUS_IBUS_CMD_IKE_IGN_RESP 0x11

/* --- Komendy emulatora CDC (zmieniacza CD) --- */
#define ORANGEBUS_IBUS_CDC_CMD_GET_STATUS 0x00
#define ORANGEBUS_IBUS_CDC_CMD_STOP_PLAYING 0x01
#define ORANGEBUS_IBUS_CDC_CMD_PAUSE_PLAYING 0x02
#define ORANGEBUS_IBUS_CDC_CMD_START_PLAYING 0x03
#define ORANGEBUS_IBUS_CDC_CMD_CHANGE_TRACK 0x0A
#define ORANGEBUS_IBUS_CDC_CMD_CHANGE_TRACK_BL 0x05

/* --- Statusy i flagi funkcjonalne CDC --- */
#define ORANGEBUS_IBUS_CDC_STAT_STOP 0x00
#define ORANGEBUS_IBUS_CDC_STAT_PLAYING 0x02
#define ORANGEBUS_IBUS_CDC_FUNC_NOT_PLAY 0x02
#define ORANGEBUS_IBUS_CDC_FUNC_PLAYING 0x09
#define ORANGEBUS_IBUS_CDC_DISC_ALL 0x3F

/* --- Komendy i statusy emulatora TEL (telefonu) --- */
#define ORANGEBUS_IBUS_TEL_CMD_LED_STATUS 0x2B
#define ORANGEBUS_IBUS_TEL_CMD_STATUS 0x2C
#define ORANGEBUS_IBUS_TEL_CMD_TITLE_TEXT 0x23

#define ORANGEBUS_IBUS_TEL_STATUS_NONE 0x00
#define ORANGEBUS_IBUS_TEL_STATUS_POWER_HF 0x10
#define ORANGEBUS_IBUS_TEL_STATUS_POWER_CALL 0x35

#define ORANGEBUS_IBUS_TEL_LED_OFF 0x00
#define ORANGEBUS_IBUS_TEL_LED_GREEN_BLINK 0x30
#define ORANGEBUS_IBUS_TEL_LED_GREEN_ON 0x10
#define ORANGEBUS_IBUS_TEL_LED_RED_ON 0x01

#define ORANGEBUS_IBUS_TEL_TITLE_DEFAULT 0x00
#define ORANGEBUS_IBUS_TEL_TITLE_ON_CALL 0x02
#define ORANGEBUS_IBUS_TEL_TITLE_OPT_SET 0x30

/* --- Stany zaplonu (IKE) --- */
#define ORANGEBUS_IBUS_IGNITION_OFF 0x00
#define ORANGEBUS_IBUS_IGNITION_KLR 0x01
#define ORANGEBUS_IBUS_IGNITION_KL15 0x03

/* --- Komendy MID (wielofunkcyjny wyswietlacz) --- */
#define ORANGEBUS_IBUS_MID_CMD_MODE 0x20
#define ORANGEBUS_IBUS_MID_CMD_SET_MODE 0x27
#define ORANGEBUS_IBUS_MID_BUTTON_PRESS 0x31
#define ORANGEBUS_IBUS_MID_MAX_CHARS 24

/* --- Glosnosc z radia --- */
#define ORANGEBUS_IBUS_RAD_VOL_DOWN 0x00
#define ORANGEBUS_IBUS_RAD_VOL_UP 0x01

/* --- Przyciski MFL (kierownica multifunkcyjna) --- */
#define ORANGEBUS_IBUS_MFL_BTN_SPEAK 0x01
#define ORANGEBUS_IBUS_MFL_BTN_VOL_UP 0x11
#define ORANGEBUS_IBUS_MFL_BTN_VOL_DOWN 0x10

/* --- DSP (procesor audio) --- */
#define ORANGEBUS_IBUS_DSP_CMD_CONFIG_SET 0x36
#define ORANGEBUS_IBUS_DSP_CFG_INPUT_RADIO 0xA1
#define ORANGEBUS_IBUS_DSP_CFG_INPUT_SPDIF 0xA0

/* --- Komendy GT (nawigacja graficzna / BMBT) --- */
#define ORANGEBUS_IBUS_CMD_GT_WRITE_TITLE 0x23
#define ORANGEBUS_IBUS_CMD_GT_WRITE_ZONE 0x62
#define ORANGEBUS_IBUS_CMD_GT_WRITE_INDEX 0x60
#define ORANGEBUS_IBUS_CMD_GT_CLEAR 0x63

/* --- MIR (Business Nav) - maks. dlugosc tekstu --- */
#define ORANGEBUS_IBUS_MIR_MAX_CHARS 11

#endif
